### ISSUE TITLE
version of glic used by `path/compiler_compat/ld` is too high

### ISSUE THREAD

**Issue by QvQQ** [hmaarrfk/arm-conda-playground#3]
I tried to `pip install numpy` but failed with an error "glibc_2.27' not found" which indicates that the specified **compat** version which means to be more compatible of `ld` requires a higher version of glibc?
Why just let the compiler makes decisions itself?

So I rename it and then everything goes well.
BTW, thanks for the arm64 conda. It helps me a lot at the end. :)

**Comment by hmaarrfk** [comment]
Are you using these?

https://anaconda.org/archiarm/

If so, please see 

https://github.com/archiconda/

and open an issue on 
https://github.com/archiconda/build-tools

**Comment by QvQQ** [comment]
Sorry about that I'm not using the latest release of archiconda. I will download and have a try with `0.2.2` version.

I reached here by search for "arm conda" at GitHub. Maybe you should consider to add some description for that real archiconda?

**Comment by hmaarrfk** [comment]
conda forge is starting to build for it.

I'm kinda helping with that, but we are stuck on tk for now

https://github.com/conda-forge/tk-feedstock/

**Comment by QvQQ** [comment]
May I help with a bit?

**Comment by hmaarrfk** [comment]
Feel free to see what is happening in here:
https://github.com/conda-forge/tk-feedstock/pull/32

Then you can fork, pull from the bot, and try something on the CIs
